name: 🚀 Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  main:
    name: 📦 Build and Push Services
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Context
        uses: actions/checkout@v4

      - name: 🛠️ Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔑 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🏗️ Build and push docker image api service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: /src/AWING_Tech_Assignment/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_AWING_TECH_ASSIGNMENT_API_SERVICE}}:latest
      - name: 🏗️ Build and push docker image web app
        uses: docker/build-push-action@v5
        with:
          context: .
          file: /src/Webs/find_treasure/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_AWING_TECH_ASSIGNMENT_WEB_APP}}:latest
